# rl/env/constants.py
TICK_HZ = 60
TICK_MS = 1000 / TICK_HZ

MAP_COLS = 15
MAP_ROWS = 13
TILE_PX = 44

SOFT_BRICK_RATE = 0.72
SPAWN_CLEAR_TILES = 3

FUSE_TICKS = round(3.0 * TICK_HZ)    # 180
SPARK_TICKS = round(0.45 * TICK_HZ)  # 27
PUSH_CHARGE_TICKS = round(0.5 * TICK_HZ)  # 30

ITEM_DROP_RATE = 0.50
ITEM_KIND_WEIGHT = 1 / 3

TRAPPED_TICKS = round(5.0 * TICK_HZ)       # 300
RESPAWN_PROTECT_TICKS = round(4.0 * TICK_HZ)  # 240

MATCH_MAX_TICKS = round(180 * TICK_HZ)  # 10800

HIT_COVER_NUM = 2
HIT_COVER_DEN = 3

SUDDEN_DEATH_START_TICK = 7200
SUDDEN_DEATH_TILE_INTERVAL = 18

PLAYER_START_HP = 1
PLAYER_START_FIRE = 2
PLAYER_MAX_FIRE = 7
PLAYER_START_CANNON = 1
PLAYER_MAX_CANNON = 6
PLAYER_START_SPEED_BONUS = 0
SPEED_BONUS_PER_ITEM = 1.0
SPEED_BONUS_CAP = 3.0

DEFAULT_MOVE_SPEED = 5.0
DEFAULT_CORNER_ASSIST = 0.25
DEFAULT_INPUT_BUFFER_MS = 120

MILLITILE = 1000

INPUT_DELAY_TICKS = 2
STALL_TIMEOUT_MS = 200
HASH_REPORT_INTERVAL = 30

RESCUE_DIST_MT = MILLITILE // 2  # 500
